version: '3.8'

services:
    db:
        image: postgres:11
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
    
    web:
        build: .
        command: bash -c "/code/docker_start_up.sh"
        environment:
        - ENVIRONMENT=dev
        volumes:
        - .:/code
        ports:
        - 8000:8000
        depends_on:
        - db

volumes:
        postgres_data:
